import type { Metadata } from 'next';

import localFont from 'next/font/local';
import './globals.css';

import { SocketProvider } from './context/SocketProvider';
import { Sixtyfour } from 'next/font/google';

const sixtyfour = Sixtyfour({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SocketProvider>
      <html lang='en' className={sixtyfour.className}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </html>
    </SocketProvider>
  );
}
